[package]
name = "the-k-th-lexicographical-string-of-all-happy-strings-of-length-n"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
