[package]
name = "leetcode"
version = "0.1.0"
authors = ["akaishi <galigalikun@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "two-sum"
path = "src/two-sum.rs"

[[bin]]
name = "add-two-numbers"
path = "src/add-two-numbers.rs"

[[bin]]
name = "longest-substring-without-repeating-characters"
path = "src/longest-substring-without-repeating-characters.rs"

[[bin]]
name = "median-of-two-sorted-arrays"
path = "src/median-of-two-sorted-arrays.rs"

[[bin]]
name = "longest-palindromic-substring"
path = "src/longest-palindromic-substring.rs"

[[bin]]
name = "zigzag-conversion"
path = "src/zigzag-conversion.rs"

[[bin]]
name = "reverse-integer"
path = "src/reverse-integer.rs"

[[bin]]
name = "string-to-integer-atoi"
path = "src/string-to-integer-atoi.rs"

[[bin]]
name = "palindrome-number"
path = "src/palindrome-number.rs"

[[bin]]
name = "regular-expression-matching"
path = "src/regular-expression-matching.rs"

[[bin]]
name = "container-with-most-water"
path = "src/container-with-most-water.rs"

[[bin]]
name = "integer-to-roman"
path = "src/integer-to-roman.rs"

[[bin]]
name = "roman-to-integer"
path = "src/roman-to-integer.rs"

[[bin]]
name = "longest-common-prefix"
path = "src/longest-common-prefix.rs"

[[bin]]
name = "3sum"
path = "src/3sum.rs"

[[bin]]
name = "3sum-closest"
path = "src/3sum-closest.rs"

[[bin]]
name = "remove-nth-node-from-end-of-list"
path = "src/remove-nth-node-from-end-of-list.rs"

[[bin]]
name = "valid-parentheses"
path = "src/valid-parentheses.rs"

[[bin]]
name = "merge-two-sorted-lists"
path = "src/merge-two-sorted-lists.rs"

[[bin]]
name = "generate-parentheses"
path = "src/generate-parentheses.rs"

[[bin]]
name = "merge-k-sorted-lists"
path = "src/merge-k-sorted-lists.rs"

[[bin]]
name = "swap-nodes-in-pairs"
path = "src/swap-nodes-in-pairs.rs"

[[bin]]
name = "reverse-nodes-in-k-group"
path = "src/reverse-nodes-in-k-group.rs"

[[bin]]
name = "remove-duplicates-from-sorted-array"
path = "src/remove-duplicates-from-sorted-array.rs"

[[bin]]
name = "remove-element"
path = "src/remove-element.rs"

[[bin]]
name = "implement-strstr"
path = "src/implement-strstr.rs"

[[bin]]
name = "divide-two-integers"
path = "src/divide-two-integers.rs"

[[bin]]
name = "substring-with-concatenation-of-all-words"
path = "src/substring-with-concatenation-of-all-words.rs"

[[bin]]
name = "longest-valid-parentheses"
path = "src/longest-valid-parentheses.rs"

[[bin]]
name = "search-in-rotated-sorted-array"
path = "src/search-in-rotated-sorted-array.rs"

[[bin]]
name = "find-first-and-last-position-of-element-in-sorted-array"
path = "src/find-first-and-last-position-of-element-in-sorted-array.rs"

[[bin]]
name = "search-insert-position"
path = "src/search-insert-position.rs"

[[bin]]
name = "count-and-say"
path = "src/count-and-say.rs"

[[bin]]
name = "combination-sum"
path = "src/combination-sum.rs"
