[package]
name = "leetcode"
version = "0.1.0"
authors = ["akaishi <galigalikun@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "two-sum"
path = "src/two-sum.rs"

[[bin]]
name = "add-two-numbers"
path = "src/add-two-numbers.rs"

[[bin]]
name = "longest-substring-without-repeating-characters"
path = "src/longest-substring-without-repeating-characters.rs"

[[bin]]
name = "median-of-two-sorted-arrays"
path = "src/median-of-two-sorted-arrays.rs"

[[bin]]
name = "longest-palindromic-substring"
path = "src/longest-palindromic-substring.rs"

[[bin]]
name = "zigzag-conversion"
path = "src/zigzag-conversion.rs"

[[bin]]
name = "reverse-integer"
path = "src/reverse-integer.rs"

[[bin]]
name = "string-to-integer-atoi"
path = "src/string-to-integer-atoi.rs"

[[bin]]
name = "palindrome-number"
path = "src/palindrome-number.rs"

[[bin]]
name = "regular-expression-matching"
path = "src/regular-expression-matching.rs"

[[bin]]
name = "container-with-most-water"
path = "src/container-with-most-water.rs"

[[bin]]
name = "integer-to-roman"
path = "src/integer-to-roman.rs"

[[bin]]
name = "roman-to-integer"
path = "src/roman-to-integer.rs"

[[bin]]
name = "longest-common-prefix"
path = "src/longest-common-prefix.rs"

[[bin]]
name = "3sum"
path = "src/3sum.rs"

[[bin]]
name = "3sum-closest"
path = "src/3sum-closest.rs"

[[bin]]
name = "4sum"
path = "src/4sum.rs"

[[bin]]
name = "letter-combinations-of-a-phone-number"
path = "src/letter-combinations-of-a-phone-number.rs"

[[bin]]
name = "remove-nth-node-from-end-of-list"
path = "src/remove-nth-node-from-end-of-list.rs"

[[bin]]
name = "valid-parentheses"
path = "src/valid-parentheses.rs"

[[bin]]
name = "merge-two-sorted-lists"
path = "src/merge-two-sorted-lists.rs"

[[bin]]
name = "generate-parentheses"
path = "src/generate-parentheses.rs"

[[bin]]
name = "merge-k-sorted-lists"
path = "src/merge-k-sorted-lists.rs"

[[bin]]
name = "swap-nodes-in-pairs"
path = "src/swap-nodes-in-pairs.rs"

[[bin]]
name = "reverse-nodes-in-k-group"
path = "src/reverse-nodes-in-k-group.rs"

[[bin]]
name = "remove-duplicates-from-sorted-array"
path = "src/remove-duplicates-from-sorted-array.rs"

[[bin]]
name = "remove-element"
path = "src/remove-element.rs"

[[bin]]
name = "implement-strstr"
path = "src/implement-strstr.rs"

[[bin]]
name = "divide-two-integers"
path = "src/divide-two-integers.rs"

[[bin]]
name = "next-permutation"
path = "src/next-permutation.rs"

[[bin]]
name = "substring-with-concatenation-of-all-words"
path = "src/substring-with-concatenation-of-all-words.rs"

[[bin]]
name = "longest-valid-parentheses"
path = "src/longest-valid-parentheses.rs"

[[bin]]
name = "search-in-rotated-sorted-array"
path = "src/search-in-rotated-sorted-array.rs"

[[bin]]
name = "find-first-and-last-position-of-element-in-sorted-array"
path = "src/find-first-and-last-position-of-element-in-sorted-array.rs"

[[bin]]
name = "search-insert-position"
path = "src/search-insert-position.rs"

[[bin]]
name = "valid-sudoku"
path = "src/valid-sudoku.rs"

[[bin]]
name = "sudoku-solver"
path = "src/sudoku-solver.rs"

[[bin]]
name = "count-and-say"
path = "src/count-and-say.rs"

[[bin]]
name = "combination-sum"
path = "src/combination-sum.rs"

[[bin]]
name = "combination-sum-ii"
path = "src/combination-sum-ii.rs"

[[bin]]
name = "first-missing-positive"
path = "src/first-missing-positive.rs"

[[bin]]
name = "trapping-rain-water"
path = "src/trapping-rain-water.rs"

[[bin]]
name = "multiply-strings"
path = "src/multiply-strings.rs"

[[bin]]
name = "merge-intervals"
path = "src/merge-intervals.rs"

[[bin]]
name = "insert-interval"
path = "src/insert-interval.rs"

[[bin]]
name = "maximum-subarray"
path = "src/maximum-subarray.rs"

[[bin]]
name = "spiral-matrix"
path = "src/spiral-matrix.rs"

[[bin]]
name = "jump-game"
path = "src/jump-game.rs"

[[bin]]
name = "permutations"
path = "src/permutations.rs"

[[bin]]
name = "length-of-last-word"
path = "src/length-of-last-word.rs"

[[bin]]
name = "spiral-matrix-ii"
path = "src/spiral-matrix-ii.rs"

[[bin]]
name = "permutation-sequence"
path = "src/permutation-sequence.rs"

[[bin]]
name = "rotate-list"
path = "src/rotate-list.rs"

[[bin]]
name = "unique-paths"
path = "src/unique-paths.rs"

[[bin]]
name = "unique-paths-ii"
path = "src/unique-paths-ii.rs"

[[bin]]
name = "minimum-path-sum"
path = "src/minimum-path-sum.rs"

[[bin]]
name = "valid-number"
path = "src/valid-number.rs"

[[bin]]
name = "plus-one"
path = "src/plus-one.rs"

[[bin]]
name = "add-binary"
path = "src/add-binary.rs"

[[bin]]
name = "text-justification"
path = "src/text-justification.rs"

[[bin]]
name = "sqrtx"
path = "src/sqrtx.rs"

[[bin]]
name = "climbing-stairs"
path = "src/climbing-stairs.rs"

[[bin]]
name = "simplify-path"
path = "src/simplify-path.rs"

[[bin]]
name = "set-matrix-zeroes"
path = "src/set-matrix-zeroes.rs"

[[bin]]
name = "search-a-2d-matrix"
path = "src/search-a-2d-matrix.rs"

[[bin]]
name = "sort-colors"
path = "src/sort-colors.rs"

[[bin]]
name = "minimum-window-substring"
path = "src/minimum-window-substring.rs"

[[bin]]
name = "combinations"
path = "src/combinations.rs"

[[bin]]
name = "subsets"
path = "src/subsets.rs"

[[bin]]
name = "word-search"
path = "src/word-search.rs"

[[bin]]
name = "remove-duplicates-from-sorted-array-ii"
path = "src/remove-duplicates-from-sorted-array-ii.rs"

[[bin]]
name = "search-in-rotated-sorted-array-ii"
path = "src/search-in-rotated-sorted-array-ii.rs"

[[bin]]
name = "remove-duplicates-from-sorted-list-ii"
path = "src/remove-duplicates-from-sorted-list-ii.rs"

[[bin]]
name = "remove-duplicates-from-sorted-list"
path = "src/remove-duplicates-from-sorted-list.rs"

[[bin]]
name = "largest-rectangle-in-histogram"
path = "src/largest-rectangle-in-histogram.rs"

[[bin]]
name = "maximal-rectangle"
path = "src/maximal-rectangle.rs"

[[bin]]
name = "partition-list"
path = "src/partition-list.rs"

[[bin]]
name = "merge-sorted-array"
path = "src/merge-sorted-array.rs"

[[bin]]
name = "gray-code"
path = "src/gray-code.rs"

[[bin]]
name = "subsets-ii"
path = "src/subsets-ii.rs"

[[bin]]
name = "decode-ways"
path = "src/decode-ways.rs"

[[bin]]
name = "reverse-linked-list-ii"
path = "src/reverse-linked-list-ii.rs"

[[bin]]
name = "restore-ip-addresses"
path = "src/restore-ip-addresses.rs"

[[bin]]
name = "validate-binary-search-tree"
path = "src/validate-binary-search-tree.rs"

[[bin]]
name = "same-tree"
path = "src/same-tree.rs"

[[bin]]
name = "rotate-image"
path = "src/rotate-image.rs"

[[bin]]
name = "group-anagrams"
path = "src/group-anagrams.rs"

[[bin]]
name = "pascals-triangle"
path = "src/pascals-triangle.rs"

[[bin]]
name = "pascals-triangle-ii"
path = "src/pascals-triangle-ii.rs"

[[bin]]
name = "triangle"
path = "src/triangle.rs"

[[bin]]
name = "best-time-to-buy-and-sell-stock"
path = "src/best-time-to-buy-and-sell-stock.rs"

[[bin]]
name = "best-time-to-buy-and-sell-stock-ii"
path = "src/best-time-to-buy-and-sell-stock-ii.rs"

[[bin]]
name = "valid-palindrome"
path = "src/valid-palindrome.rs"

[[bin]]
name = "single-number"
path = "src/single-number.rs"

[[bin]]
name = "single-number-ii"
path = "src/single-number-ii.rs"

[[bin]]
name = "insertion-sort-list"
path = "src/insertion-sort-list.rs"

[[bin]]
name = "sort-list"
path = "src/sort-list.rs"

[[bin]]
name = "reorder-list"
path = "src/reorder-list.rs"

[[bin]]
name = "lru-cache"
path = "src/lru-cache.rs"

[[bin]]
name = "evaluate-reverse-polish-notation"
path = "src/evaluate-reverse-polish-notation.rs"

[[bin]]
name = "reverse-words-in-a-string"
path = "src/reverse-words-in-a-string.rs"

[[bin]]
name = "maximum-product-subarray"
path = "src/maximum-product-subarray.rs"

[[bin]]
name = "find-minimum-in-rotated-sorted-array"
path = "src/find-minimum-in-rotated-sorted-array.rs"

[[bin]]
name = "min-stack"
path = "src/min-stack.rs"

[[bin]]
name = "find-peak-element"
path = "src/find-peak-element.rs"

[[bin]]
name = "maximum-gap"
path = "src/maximum-gap.rs"

[[bin]]
name = "two-sum-ii-input-array-is-sorted"
path = "src/two-sum-ii-input-array-is-sorted.rs"

[[bin]]
name = "find-minimum-in-rotated-sorted-array-ii"
path = "src/find-minimum-in-rotated-sorted-array-ii.rs"

[[bin]]
name = "compare-version-numbers"
path = "src/compare-version-numbers.rs"
