[package]
name = "leetcode"
version = "0.1.0"
authors = ["akaishi <galigalikun@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "length_of_longest_substring"
path = "src/length_of_longest_substring.rs"

[[bin]]
name = "median-of-two-sorted-arrays"
path = "src/median-of-two-sorted-arrays.rs"
