[package]
name = "check-if-a-string-contains-all-binary-codes-of-size-k"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
