[package]
name = "people-whose-list-of-favorite-companies-is-not-a-subset-of-another-list"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
