[package]
name = "number-of-ways-to-stay-in-the-same-place-after-some-steps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
