[package]
name = "build-array-where-you-can-find-the-maximum-exactly-k-comparisons"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
