fn main() {
    assert_eq!(
        Solution::find_anagrams("cbaebabacd".to_string(), "abc".to_string()),
        vec![0, 6]
    );
    assert_eq!(
        Solution::find_anagrams("abab".to_string(), "ab".to_string()),
        vec![0, 1, 2]
    );
    assert_eq!(
        Solution::find_anagrams("aaaaaaaaaa".to_string(), "aaaaaaaaaaaaa".to_string()),
        vec![]
    );
    assert_eq!(Solution::find_anagrams("kzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlrykzexfqiudtwvpjnhgocasbmlr".to_string(), "ykzexfqiudtwvpjnhgocasbmlr".to_string()), vec![]);
}

pub struct Solution {}
// https://medium.com/@yzhua3/leetcode-find-all-anagrams-in-a-string-b535d8ad6022
impl Solution {
    fn is_anagram(s: String, start: usize, end: usize, p: Vec<i32>) -> bool {
        let mut a = vec![0; 26];
        for i in start..=end {
            let c = s.chars().nth(i).unwrap();
            if p[c as usize - 97] == 0 {
                return false;
            }
            a[c as usize - 97] += 1;
            if p[c as usize - 97] < a[c as usize - 97] {
                return false;
            }
        }
        return true;
    }
    pub fn find_anagrams(s: String, p: String) -> Vec<i32> {
        if s.len() < p.len() {
            return vec![];
        }
        let mut a = vec![0; 26];
        for c in p.chars() {
            a[c as usize - 97] += 1;
        }
        let mut result = vec![];
        for i in 0..=s.len() - p.len() {
            let c = s.chars().nth(i).unwrap();
            if a[c as usize - 97] == 0 {
                continue;
            }
            if Solution::is_anagram(s.clone(), i, i + p.len() - 1, a.clone()) {
                result.push(i as i32);
            }
        }
        return result;
    }
}
